[package]
name = "twitch-lib"
version = "0.1.0"
edition = "2024"

[features]
alpha = ["mcv-plugin-telemetry/alpha"]
beta = ["mcv-plugin-telemetry/beta"]
stable = ["mcv-plugin-telemetry/stable"]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = "2.5.8"
anyhow = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
mcv-plugin-telemetry = { path = "../mcv-plugin-telemetry" }
dotenvy = "0.15"
