[package]
name = "twitch-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = "2.5.8"
anyhow = { workspace = true }
chrono = { workspace = true }
dotenvy = "0.15"