[workspace]
members = [
    "crates/mcv-common",
    "crates/mcv-messages",
    "crates/mcv-plugin-interface",
    "crates/mcv-plugin-exe-interface",
    "crates/mcv-plugin-loader",
    "crates/mcv-plugin-loader-v3",
    "crates/mcv-updater",
    "crates/mcv-log-schema",
    "crates/mcv-log-core",
    "crates/mcv-plugin-telemetry",
    "crates/mcv-settings-core",
    "crates/mcv-core",
    "crates/plugin-dummy",
    "crates/plugin-exe-manager",
    "crates/plugin-exe-manager-v3",
    "crates/plugin-youtube-live",
    "apps/mcv/src-tauri",
    "apps/log-viewer/src-tauri",
    "apps/exe-plugin-sample/src-tauri",
    "crates/twitch-lib",
    "xtask",
    "crates/youtube-live-lib",
    "crates/plugin-sample-v2",
    "crates/plugin-abi-helper",
    "crates/plugin-sample-v3",
    "crates/export-plugin-v3-macros",
    "examples/youtube-live-lib-getcomments",
    "crates/plugin-chrome-cookie",
    "crates/plugin-cookies-txt",
    "crates/plugin-bouyomi",
    "crates/plugin-twitch",
    "crates/plugin-twicas",
    "crates/plugin-kick",
    "crates/plugin-nicolive",
    "crates/nicolive-lib",
]
resolver = "2"

[workspace.dependencies]
actix = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "v5", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tauri = { version = "2.9.1", features = [] }
