[workspace]
members = [
    "crates/mcv-common",
    "crates/mcv-messages",
    "crates/mcv-plugin-interface",
    "crates/mcv-plugin-loader",
    "crates/mcv-updater",
    "crates/mcv-logger",
    "crates/mcv-core",
    "crates/plugin-dummy",
    "apps/mcv/src-tauri",
    "apps/installer/src-tauri", "apps/package_release", "crates/twitch-lib",
]
resolver = "2"

[workspace.dependencies]
actix = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tauri = { version = "2.1", features = [] }
