[package]
name = "mcv-plugin-telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
mcv-log-schema = { path = "../mcv-log-schema" }
# Tracing ecosystem
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }

# Local crates
mcv-messages = { path = "../mcv-messages" }
mcv-plugin-interface = { path = "../mcv-plugin-interface" }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# UUID
uuid = { workspace = true }

# Time
chrono = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Stacktrace
backtrace = { workspace = true }

[features]
alpha = ["mcv-log-schema/alpha"]
beta = ["mcv-log-schema/beta"]
stable = ["mcv-log-schema/stable"]
