[package]
name = "plugin-sample-v3"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
mcv-messages = { path = "../../crates/mcv-messages" }
plugin-abi-helper = { path = "../plugin-abi-helper" }
async-trait = "0.1"
serde_json = "1.0"
tracing = "0.1"
uuid = "1"

[features]
alpha = []
beta = []
stable = []
