[package]
name = "plugin-sample-v2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
plugin-abi-helper = { path = "../plugin-abi-helper" }
mcv-plugin-interface = { path = "../mcv-plugin-interface" }
mcv-messages = { path = "../mcv-messages" }
async-trait = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }

[features]
alpha = []
beta = []
stable = []
