[package]
name = "youtube-live-lib-getcomments"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "youtube-live-lib-getcomments"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json", "gzip", "stream", "deflate"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mcv-log-core = { path = "../../crates/mcv-log-core" }
tracing = "0.1"
tracing-subscriber = "0.3"
youtube-live-lib = { path = "../../crates/youtube-live-lib" }
clap = { version = "4.0", features = ["derive"] }

[features]
alpha = ["mcv-log-core/alpha", "youtube-live-lib/alpha"]
beta = ["mcv-log-core/beta", "youtube-live-lib/beta"]
stable = ["mcv-log-core/stable", "youtube-live-lib/stable"]
