[package]
name = "mcv-core"
version = "0.1.0"
edition = "2021"

[dependencies]
mcv-common = { path = "../mcv-common" }
mcv-messages = { path = "../mcv-messages" }
mcv-plugin-interface = { path = "../mcv-plugin-interface" }
mcv-plugin-loader = { path = "../mcv-plugin-loader" }
mcv-plugin-loader-v3 = { path = "../mcv-plugin-loader-v3" }
mcv-logger = { path = "../mcv-logger" }
plugin-abi-helper = { path = "../plugin-abi-helper" }
actix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
once_cell = "1.20"
libloading = "0.8"

[features]
alpha = ["mcv-logger/alpha","mcv-plugin-loader-v3/alpha","plugin-abi-helper/alpha"]
beta = ["mcv-logger/beta","mcv-plugin-loader-v3/beta","plugin-abi-helper/beta"]
stable = ["mcv-logger/stable","mcv-plugin-loader-v3/stable","plugin-abi-helper/stable"]
