[package]
name = "mcv-core"
version = "0.1.0"
edition = "2021"

[dependencies]
mcv-messages = { path = "../mcv-messages" }
mcv-plugin-interface = { path = "../mcv-plugin-interface" }
mcv-plugin-loader = { path = "../mcv-plugin-loader" }
actix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
