[package]
name = "mcv-core"
version = "0.1.0"
edition = "2021"

[dependencies]
mcv-common = { path = "../mcv-common" }
mcv-messages = { path = "../mcv-messages" }
mcv-plugin-interface = { path = "../mcv-plugin-interface" }
mcv-plugin-loader = { path = "../mcv-plugin-loader" }
mcv-plugin-loader-v3 = { path = "../mcv-plugin-loader-v3" }
mcv-log-core = { path = "../mcv-log-core" }
mcv-settings-core = { path = "../mcv-settings-core" }
plugin-abi-helper = { path = "../plugin-abi-helper" }
actix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
indexmap = "2.0"
libloading = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = "3.8"

[features]
alpha = ["mcv-log-core/alpha","mcv-plugin-loader-v3/alpha","plugin-abi-helper/alpha"]
beta = ["mcv-log-core/beta","mcv-plugin-loader-v3/beta","plugin-abi-helper/beta"]
stable = ["mcv-log-core/stable","mcv-plugin-loader-v3/stable","plugin-abi-helper/stable"]
