[package]
name = "plugin-twicas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
alpha = ["mcv-plugin-telemetry/alpha", "plugin-abi-helper/alpha"]
beta = ["mcv-plugin-telemetry/beta", "plugin-abi-helper/beta"]
stable = ["mcv-plugin-telemetry/stable", "plugin-abi-helper/stable"]

[dependencies]
mcv-common = { path = "../../crates/mcv-common" }
mcv-messages = { path = "../../crates/mcv-messages" }
mcv-plugin-interface = { path = "../../crates/mcv-plugin-interface" }
twicas-lib = { path = "../../crates/twicas-lib" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
rand = "0.10"
once_cell = "1.20"
mcv-plugin-telemetry = { path = "../../crates/mcv-plugin-telemetry" }
tracing = "0.1"
plugin-abi-helper = { path = "../../crates/plugin-abi-helper" }
regex = "1.12.3"
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "multipart", "cookies"] }
