[package]
name = "mcv-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "stream"] }
semver = "1.0"
sha2 = "0.10"
tokio = { workspace = true, features = ["fs", "io-util"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
