cargo xtask dist --channel beta `
    --plugin bouyomi `
    --plugin chrome-cookie `
    --plugin firefox-cookie `
    --plugin cookies-txt `
    --plugin exe-manager-v3 `
    --plugin twitch `
    --plugin twicas `
    --plugin youtubelive `
    --plugin kick `
    --plugin whowatch
