[package]
name = "plugin-dummy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
alpha = []
beta = []
stable = []

[dependencies]
mcv-messages = { path = "../../crates/mcv-messages" }
mcv-plugin-interface = { path = "../../crates/mcv-plugin-interface" }
mcv-plugin-telemetry = { path = "../../crates/mcv-plugin-telemetry" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
rand = "0.8"
once_cell = "1.20"
