[package]
name = "exe-plugin-sample"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# Tauri
tauri = { workspace = true, features = ["devtools"] }
tauri-plugin-shell = "2"
serde = { workspace = true }
serde_json = { workspace = true }

# MCV dependencies
mcv-plugin-exe-interface = { path = "../../../crates/mcv-plugin-exe-interface" }
mcv-messages = { path = "../../../crates/mcv-messages" }

# Async runtime
tokio = { workspace = true }

# UUID
uuid = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

chrono = { workspace = true }
rusqlite = { workspace = true }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2"

[features]
alpha = []
beta = []
stable = []
